version: '3.0'
services:
  posterpal:
    build:
      context: '.'
      dockerfile: Dockerfile
    volumes:
      - ./data/processing:/data/processing/
      - ./data/assets:/data/assets/
      - ./data/backup:/data/backup/
      - ./tests/movies:/data/movies/
      - ./tests/shows:/data/shows/
